[WIP] Remove the double encoding of the date for cases search
gridsuite/merge-orchestrator pull request #7
Opened 2020-08-27 14:12 UTC by SlimaneAmar

Signed-off-by: Slimane AMAR <slimane.amar@rte-france.com>

2020-08-27 15:18 UTC, FranckLecuyer requested changes

2020-08-27 15:18 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/merge/orchestrator/server/CaseFetcherService.java
> +                .append(tsos.stream().collect(Collectors.joining(" OR ", "(", ")")).toString());
You can remove toString() here

2020-08-27 16:06 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/merge/orchestrator/server/CaseFetcherService.java
> +                .append(tsos.stream().collect(Collectors.joining(" OR ", "(", ")")).toString());
Done

2020-08-28 06:40 UTC, FranckLecuyer approved these changes

2020-08-28 09:27 UTC, merged